[build]
filehash = false

[watch]
ignore = ["target_ssr"]
# Local version of Sycamore
watch = ["./", "../sycamore/docs"]

[serve]
no_spa = true
port = 8000   # We are using another server for serving the static files since we are using a MPA architecture.

[[hooks]]
stage = "build"
command = "cargo"
command_arguments = ["build", "--target-dir", "target_ssr/"]

[[hooks]]
stage = "post_build"
command = "cargo"
command_arguments = ["run", "--target-dir", "target_ssr/"]

[tools]
tailwindcss = "4.0.6"
