name: Sync Submodule

on:
  # This workflow is triggered every time the docs is changed in sycamore-rs/sycamore
  workflow_dispatch:

jobs:
  sync:
    name: Sync Submodule
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          subodules: true

      - name: update submodule git references
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
